// Generated by tools/make_fixture.py. Invented sample data in the /state shape.
window.entropyFixture({
 "now": 1790000000.0,
 "workspaceCount": 7,
 "status": "",
 "windows": 2,
 "groups": {
  "needs_input": [
   {
    "sid": "d20af98a-9ad4-436e-bdc5-8a1a972cb280",
    "state": "needs_input",
    "since": 1789999160.0,
    "last": 1789999160.0,
    "ws": "Ledger",
    "wid": "C5C40ECC-ED43-40DB-8ABC-99A7C85FFD63",
    "surface": "AD87DB8B-66F6-4EAD-949F-C9BD9A60F828",
    "title": "Payments webhook retries",
    "repo": "ledger-api",
    "kind": "claude",
    "color": "#FF6B6B",
    "cwd": "/Users/dev/code/ledger-api",
    "priority": {
     "level": "urgent",
     "reason": "Prod deploy blocked on your approval",
     "sticky": false,
     "set_at": 1789999640.0
    },
    "detail": {
     "hook": {
      "last_hook": "Stop",
      "tool": null,
      "tool_at": null,
      "tool_calls": 57,
      "prompts": 6,
      "turn_started": 1789998980.0,
      "tool_errors": null,
      "subagents_done": 2
     },
     "session": {
      "pid": 40024,
      "started_at": 1789982000.0,
      "account": "work",
      "transcript": "/Users/dev/.claude/projects/-Users-dev-code-ledger-api/d20af98a-9ad4-436e-bdc5-8a1a972cb280.jsonl"
     },
     "proc": {
      "cpu": 1,
      "rss_mb": 160,
      "etime": "05:00:00",
      "children": 1
     },
     "transcript": {
      "ai_title": "Payments webhook retries",
      "model": "claude-opus-5",
      "effort": "high",
      "permission_mode": "auto",
      "mode": "normal",
      "git_branch": "fix/webhook-retries",
      "version": "2.1.280",
      "entrypoint": "cli",
      "turns": 6,
      "context_tokens": 120000,
      "output_tokens": 48000,
      "tool_errors": 1,
      "last_turn_ms": 42000,
      "message_count": 180,
      "last_user": "Retries are double-charging on 502s. Find the cause and fix it before the 3pm deploy.",
      "last_user_at": 1789998980.0,
      "last_prompt": "Retries are double-charging on 502s. Find the cause and fix it before the 3pm deploy.",
      "last_reply": null,
      "last_assistant_at": 1789999160.0,
      "files_edited": 2,
      "recent_files": [
       "retry.ts",
       "webhooks.ts"
      ],
      "top_tools": [
       [
        "Bash",
        31
       ],
       [
        "Edit",
        12
       ],
       [
        "Read",
        9
       ],
       [
        "Grep",
        4
       ]
      ],
      "question": {
       "text": "The idempotency key is missing on the retry path. How should I backfill keys for the 1,204 in-flight webhooks?",
       "options": [
        "Derive from event id",
        "Generate new + dedupe table",
        "Skip backfill"
       ],
       "more": 1
      },
      "pending_tool": {
       "name": "AskUserQuestion",
       "summary": "The idempotency key is missing\u2026"
      },
      "todos": {
       "done": 4,
       "total": 6,
       "active": "Backfilling idempotency keys"
      }
     },
     "workspace": {
      "description": null,
      "pinned": false,
      "group": "Client A",
      "unread": 0,
      "window": 1,
      "branch": "fix/webhook-retries",
      "dirty": true,
      "ports": [],
      "prs": [
       "https://github.com/acme/ledger-api/pull/412"
      ],
      "latest_notification": null,
      "project_root": "/Users/dev/code/ledger-api",
      "remote": false
     },
     "git": {
      "branch": "fix/webhook-retries",
      "changed": 3,
      "ahead": 2,
      "behind": 0,
      "last_commit": "Tidy imports",
      "last_commit_at": 1789992800.0
     },
     "notification": null
    }
   },
   {
    "sid": "978660e4-9eef-41b7-82fb-a6547b164b48",
    "state": "needs_input",
    "since": 1789998140.0,
    "last": 1789998140.0,
    "ws": "Website",
    "wid": "2BACB1B8-9976-4108-BF6D-1E24F93C2721",
    "surface": "DB18934A-ECD5-445C-82E3-161FD68D212E",
    "title": "Onboarding copy refresh",
    "repo": "marketing-site",
    "kind": "claude",
    "color": null,
    "cwd": "/Users/dev/code/marketing-site",
    "priority": null,
    "detail": {
     "hook": {
      "last_hook": "Stop",
      "tool": null,
      "tool_at": null,
      "tool_calls": 57,
      "prompts": 6,
      "turn_started": 1789997960.0,
      "tool_errors": null,
      "subagents_done": 2
     },
     "session": {
      "pid": 40023,
      "started_at": 1789982000.0,
      "account": "default",
      "transcript": "/Users/dev/.claude/projects/-Users-dev-code-marketing-site/978660e4-9eef-41b7-82fb-a6547b164b48.jsonl"
     },
     "proc": {
      "cpu": 1,
      "rss_mb": 160,
      "etime": "05:00:00",
      "children": 1
     },
     "transcript": {
      "ai_title": "Onboarding copy refresh",
      "model": "claude-sonnet-5",
      "effort": "high",
      "permission_mode": "auto",
      "mode": "normal",
      "git_branch": "main",
      "version": "2.1.280",
      "entrypoint": "cli",
      "turns": 6,
      "context_tokens": 120000,
      "output_tokens": 48000,
      "tool_errors": 1,
      "last_turn_ms": 42000,
      "message_count": 180,
      "last_user": "Rewrite the onboarding emails to be shorter and warmer.",
      "last_user_at": 1789997960.0,
      "last_prompt": "Rewrite the onboarding emails to be shorter and warmer.",
      "last_reply": null,
      "last_assistant_at": 1789998140.0,
      "files_edited": 0,
      "recent_files": [],
      "top_tools": [
       [
        "Bash",
        31
       ],
       [
        "Edit",
        12
       ],
       [
        "Read",
        9
       ],
       [
        "Grep",
        4
       ]
      ],
      "plan": "## Plan\n1. Audit the 5 onboarding emails and their open rates\n2. Rewrite subject lines (A/B two variants each)\n3. Cut body copy ~40%, one CTA per email\n4. Update templates in /emails and preview locally",
      "pending_tool": {
       "name": "ExitPlanMode",
       "summary": "## Plan 1. Audit the 5 onboarding emails\u2026"
      }
     },
     "workspace": {
      "description": null,
      "pinned": false,
      "group": "Personal",
      "unread": 0,
      "window": 1,
      "branch": "main",
      "dirty": false,
      "ports": [],
      "prs": [],
      "latest_notification": null,
      "project_root": "/Users/dev/code/marketing-site",
      "remote": false
     },
     "git": {
      "branch": "main",
      "changed": 0,
      "ahead": 0,
      "behind": 0,
      "last_commit": "Tidy imports",
      "last_commit_at": 1789992800.0
     },
     "notification": null
    }
   },
   {
    "sid": "2e7b5aec-9ef9-492a-bf96-651b3e666072",
    "state": "needs_input",
    "since": 1789999880.0,
    "last": 1789999880.0,
    "ws": "Ledger",
    "wid": "DA7E0E15-7779-4CE7-B2E5-D2DC9A28CF33",
    "surface": "D14E3A84-4BA7-44E7-B878-CA526F1E836F",
    "title": "Flaky e2e investigation",
    "repo": "ledger-web",
    "kind": "claude",
    "color": "#FF6B6B",
    "cwd": "/Users/dev/code/ledger-web",
    "priority": null,
    "detail": {
     "hook": {
      "last_hook": "Stop",
      "tool": null,
      "tool_at": null,
      "tool_calls": 57,
      "prompts": 6,
      "turn_started": 1789999700.0,
      "tool_errors": null,
      "subagents_done": 2
     },
     "session": {
      "pid": 40023,
      "started_at": 1789982000.0,
      "account": "work",
      "transcript": "/Users/dev/.claude/projects/-Users-dev-code-ledger-web/2e7b5aec-9ef9-492a-bf96-651b3e666072.jsonl"
     },
     "proc": {
      "cpu": 1,
      "rss_mb": 160,
      "etime": "05:00:00",
      "children": 1
     },
     "transcript": {
      "ai_title": "Flaky e2e investigation",
      "model": "claude-opus-5",
      "effort": "high",
      "permission_mode": "auto",
      "mode": "normal",
      "git_branch": "chore/e2e-flake",
      "version": "2.1.280",
      "entrypoint": "cli",
      "turns": 6,
      "context_tokens": 120000,
      "output_tokens": 48000,
      "tool_errors": 1,
      "last_turn_ms": 42000,
      "message_count": 180,
      "last_user": "The checkout e2e test fails ~1 in 5 runs on CI. Figure out why.",
      "last_user_at": 1789999700.0,
      "last_prompt": "The checkout e2e test fails ~1 in 5 runs on CI. Figure out why.",
      "last_reply": null,
      "last_assistant_at": 1789999880.0,
      "files_edited": 0,
      "recent_files": [],
      "top_tools": [
       [
        "Bash",
        31
       ],
       [
        "Edit",
        12
       ],
       [
        "Read",
        9
       ],
       [
        "Grep",
        4
       ]
      ],
      "pending_tool": {
       "name": "Bash",
       "summary": "docker compose -f ci/compose.yml up -d postgres && pnpm test:e2e --repeat-each=20 checkout.spec.ts"
      }
     },
     "workspace": {
      "description": null,
      "pinned": false,
      "group": "Client A",
      "unread": 0,
      "window": 1,
      "branch": "chore/e2e-flake",
      "dirty": false,
      "ports": [],
      "prs": [],
      "latest_notification": null,
      "project_root": "/Users/dev/code/ledger-web",
      "remote": false
     },
     "git": {
      "branch": "chore/e2e-flake",
      "changed": 0,
      "ahead": 0,
      "behind": 0,
      "last_commit": "Tidy imports",
      "last_commit_at": 1789992800.0
     },
     "notification": null
    }
   },
   {
    "sid": "1e180f2c-9f7b-4389-abef-ec6500a958b2",
    "state": "needs_input",
    "since": 1789997120.0,
    "last": 1789997120.0,
    "ws": "Docs",
    "wid": "CAD5EBBD-A7CD-4E77-954B-11317073941F",
    "surface": "1FD6D882-7FC8-426E-ACD4-FF7F29425B5B",
    "title": "Docs site search",
    "repo": "docs",
    "kind": "claude",
    "color": null,
    "cwd": "/Users/dev/code/docs",
    "priority": null,
    "detail": {
     "hook": {
      "last_hook": "Stop",
      "tool": null,
      "tool_at": null,
      "tool_calls": 57,
      "prompts": 6,
      "turn_started": 1789996940.0,
      "tool_errors": null,
      "subagents_done": 2
     },
     "session": {
      "pid": 40016,
      "started_at": 1789982000.0,
      "account": "default",
      "transcript": "/Users/dev/.claude/projects/-Users-dev-code-docs/1e180f2c-9f7b-4389-abef-ec6500a958b2.jsonl"
     },
     "proc": {
      "cpu": 1,
      "rss_mb": 160,
      "etime": "05:00:00",
      "children": 1
     },
     "transcript": {
      "ai_title": "Docs site search",
      "model": "claude-opus-5",
      "effort": "high",
      "permission_mode": "auto",
      "mode": "normal",
      "git_branch": "main",
      "version": "2.1.280",
      "entrypoint": "cli",
      "turns": 6,
      "context_tokens": 120000,
      "output_tokens": 48000,
      "tool_errors": 1,
      "last_turn_ms": 42000,
      "message_count": 180,
      "last_user": "Add search to the docs site.",
      "last_user_at": 1789996940.0,
      "last_prompt": "Add search to the docs site.",
      "last_reply": "Search is wired up with a client-side index (38 KB gzipped). One decision for you: index the API reference too? It triples the index size.",
      "last_assistant_at": 1789997120.0,
      "files_edited": 0,
      "recent_files": [],
      "top_tools": [
       [
        "Bash",
        31
       ],
       [
        "Edit",
        12
       ],
       [
        "Read",
        9
       ],
       [
        "Grep",
        4
       ]
      ]
     },
     "workspace": {
      "description": null,
      "pinned": false,
      "group": "Personal",
      "unread": 0,
      "window": 1,
      "branch": "main",
      "dirty": false,
      "ports": [],
      "prs": [],
      "latest_notification": "Search is wired up with a client-side index (38 KB gzipped). One decision for you: index the API reference too?",
      "project_root": "/Users/dev/code/docs",
      "remote": false
     },
     "git": {
      "branch": "main",
      "changed": 0,
      "ahead": 0,
      "behind": 0,
      "last_commit": "Tidy imports",
      "last_commit_at": 1789992800.0
     },
     "notification": {
      "title": "Claude Code",
      "subtitle": "Completed in Docs",
      "body": "Search is wired up with a client-side index (38 KB gzipped). One decision for you: index the API reference too?",
      "created_at": "2026-09-23T17:00:00Z",
      "at": 1789997120.0,
      "read": false
     }
    }
   }
  ],
  "working": [
   {
    "sid": "4b46f550-af08-4122-a124-e33d17e86305",
    "state": "working",
    "since": 1789999460.0,
    "last": 1789999460.0,
    "ws": "Atlas",
    "wid": "A85A5024-9294-4E72-A636-34AE87ACCC16",
    "surface": "8F79E707-15C6-4A07-977C-74275C929A76",
    "title": "Migrate auth to OIDC",
    "repo": "atlas",
    "kind": "claude",
    "color": "#4C8DFF",
    "cwd": "/Users/dev/code/atlas",
    "priority": {
     "level": "high",
     "reason": "Security review Friday",
     "sticky": true,
     "set_at": 1789997000.0
    },
    "detail": {
     "hook": {
      "last_hook": "PreToolUse",
      "tool": "Edit",
      "tool_at": 1789999960.0,
      "tool_calls": 57,
      "prompts": 6,
      "turn_started": 1789999820.0,
      "tool_errors": null,
      "subagents_done": 2
     },
     "session": {
      "pid": 40020,
      "started_at": 1789982000.0,
      "account": "work",
      "transcript": "/Users/dev/.claude/projects/-Users-dev-code-atlas/4b46f550-af08-4122-a124-e33d17e86305.jsonl"
     },
     "proc": {
      "cpu": 14,
      "rss_mb": 410,
      "etime": "05:00:00",
      "children": 1
     },
     "transcript": {
      "ai_title": "Migrate auth to OIDC",
      "model": "claude-opus-5",
      "effort": "high",
      "permission_mode": "auto",
      "mode": "normal",
      "git_branch": "feat/oidc",
      "version": "2.1.280",
      "entrypoint": "cli",
      "turns": 6,
      "context_tokens": 182000,
      "output_tokens": 121000,
      "tool_errors": 1,
      "last_turn_ms": 42000,
      "message_count": 180,
      "last_user": "Replace the session-cookie auth with OIDC. Keep the old path behind a flag for a week.",
      "last_user_at": 1789999280.0,
      "last_prompt": "Replace the session-cookie auth with OIDC. Keep the old path behind a flag for a week.",
      "last_reply": "Token refresh works end to end. Moving on to the admin routes.",
      "last_assistant_at": 1789999460.0,
      "files_edited": 4,
      "recent_files": [
       "auth.ts",
       "session.ts",
       "oidc.ts",
       "flags.ts"
      ],
      "top_tools": [
       [
        "Bash",
        31
       ],
       [
        "Edit",
        12
       ],
       [
        "Read",
        9
       ],
       [
        "Grep",
        4
       ]
      ],
      "pending_tool": {
       "name": "Edit",
       "summary": "middleware/auth.ts"
      },
      "todos": {
       "done": 3,
       "total": 7,
       "active": "Porting admin routes to OIDC guards"
      }
     },
     "workspace": {
      "description": null,
      "pinned": false,
      "group": "Client B",
      "unread": 0,
      "window": 1,
      "branch": "feat/oidc",
      "dirty": true,
      "ports": [],
      "prs": [],
      "latest_notification": null,
      "project_root": "/Users/dev/code/atlas",
      "remote": false
     },
     "git": {
      "branch": "feat/oidc",
      "changed": 11,
      "ahead": 5,
      "behind": 1,
      "last_commit": "Tidy imports",
      "last_commit_at": 1789992800.0
     },
     "notification": null
    }
   },
   {
    "sid": "e081d1de-b525-41ca-bc50-42d6c6a1bcbf",
    "state": "working",
    "since": 1789999760.0,
    "last": 1789999760.0,
    "ws": "Nimbus",
    "wid": "BD4B555D-8535-43EA-B20A-9D80379246D8",
    "surface": "9110E683-C509-48C8-8ECE-1BD510AB7C76",
    "title": "Dashboard charts",
    "repo": "nimbus",
    "kind": "claude",
    "color": null,
    "cwd": "/Users/dev/code/nimbus",
    "priority": null,
    "detail": {
     "hook": {
      "last_hook": "PreToolUse",
      "tool": "Bash",
      "tool_at": 1789999960.0,
      "tool_calls": 57,
      "prompts": 6,
      "turn_started": 1789999820.0,
      "tool_errors": null,
      "subagents_done": 2
     },
     "session": {
      "pid": 40016,
      "started_at": 1789982000.0,
      "account": "default",
      "transcript": "/Users/dev/.claude/projects/-Users-dev-code-nimbus/e081d1de-b525-41ca-bc50-42d6c6a1bcbf.jsonl"
     },
     "proc": {
      "cpu": 62,
      "rss_mb": 520,
      "etime": "05:00:00",
      "children": 1
     },
     "transcript": {
      "ai_title": "Dashboard charts",
      "model": "claude-sonnet-5",
      "effort": "medium",
      "permission_mode": "auto",
      "mode": "normal",
      "git_branch": "feat/charts",
      "version": "2.1.280",
      "entrypoint": "cli",
      "turns": 6,
      "context_tokens": 120000,
      "output_tokens": 48000,
      "tool_errors": 1,
      "last_turn_ms": 42000,
      "message_count": 180,
      "last_user": "Add the usage-over-time chart to the dashboard.",
      "last_user_at": 1789999580.0,
      "last_prompt": "Add the usage-over-time chart to the dashboard.",
      "last_reply": "Chart renders; running the visual regression suite now.",
      "last_assistant_at": 1789999760.0,
      "files_edited": 0,
      "recent_files": [],
      "top_tools": [
       [
        "Bash",
        31
       ],
       [
        "Edit",
        12
       ],
       [
        "Read",
        9
       ],
       [
        "Grep",
        4
       ]
      ],
      "pending_tool": {
       "name": "Bash",
       "summary": "pnpm test:visual --update-snapshots=false"
      }
     },
     "workspace": {
      "description": null,
      "pinned": false,
      "group": "Personal",
      "unread": 0,
      "window": 1,
      "branch": "feat/charts",
      "dirty": true,
      "ports": [
       3000,
       6006
      ],
      "prs": [
       "https://github.com/dev/nimbus/pull/88"
      ],
      "latest_notification": null,
      "project_root": "/Users/dev/code/nimbus",
      "remote": false
     },
     "git": {
      "branch": "feat/charts",
      "changed": 6,
      "ahead": 0,
      "behind": 0,
      "last_commit": "Tidy imports",
      "last_commit_at": 1789992800.0
     },
     "notification": null
    }
   }
  ],
  "idle": [
   {
    "sid": "c3f0e287-6f6a-4b71-9391-dd72be43f27d",
    "state": "idle",
    "since": 1789992800.0,
    "last": 1789992800.0,
    "ws": "Nimbus",
    "wid": "5A3110BD-250A-4B6A-A2E9-B148F7D91FD6",
    "surface": "D7169BAE-7E4A-4281-885F-6943BB150BB4",
    "title": "Release notes draft",
    "repo": "nimbus",
    "kind": "claude",
    "color": null,
    "cwd": "/Users/dev/code/nimbus",
    "priority": {
     "level": "low",
     "reason": "Whenever, before v2.4",
     "sticky": true,
     "set_at": 1789989200.0
    },
    "detail": {
     "hook": {
      "last_hook": "Stop",
      "tool": null,
      "tool_at": null,
      "tool_calls": 57,
      "prompts": 6,
      "turn_started": 1789992620.0,
      "tool_errors": null,
      "subagents_done": 2
     },
     "session": {
      "pid": 40019,
      "started_at": 1789982000.0,
      "account": "default",
      "transcript": "/Users/dev/.claude/projects/-Users-dev-code-nimbus/c3f0e287-6f6a-4b71-9391-dd72be43f27d.jsonl"
     },
     "proc": {
      "cpu": 1,
      "rss_mb": 160,
      "etime": "05:00:00",
      "children": 1
     },
     "transcript": {
      "ai_title": "Release notes draft",
      "model": "claude-opus-5",
      "effort": "high",
      "permission_mode": "auto",
      "mode": "normal",
      "git_branch": "main",
      "version": "2.1.280",
      "entrypoint": "cli",
      "turns": 6,
      "context_tokens": 120000,
      "output_tokens": 48000,
      "tool_errors": 1,
      "last_turn_ms": 42000,
      "message_count": 180,
      "last_user": "Draft release notes for v2.4 from the merged PRs.",
      "last_user_at": 1789992620.0,
      "last_prompt": "Draft release notes for v2.4 from the merged PRs.",
      "last_reply": "Draft is in RELEASE_NOTES.md: 14 changes grouped into Features, Fixes, and Internal.",
      "last_assistant_at": 1789992800.0,
      "files_edited": 0,
      "recent_files": [],
      "top_tools": [
       [
        "Bash",
        31
       ],
       [
        "Edit",
        12
       ],
       [
        "Read",
        9
       ],
       [
        "Grep",
        4
       ]
      ]
     },
     "workspace": {
      "description": null,
      "pinned": false,
      "group": "Personal",
      "unread": 0,
      "window": 1,
      "branch": "main",
      "dirty": false,
      "ports": [],
      "prs": [],
      "latest_notification": "Draft is in RELEASE_NOTES.md: 14 changes grouped into Features, Fixes, and Internal.",
      "project_root": "/Users/dev/code/nimbus",
      "remote": false
     },
     "git": {
      "branch": "main",
      "changed": 0,
      "ahead": 0,
      "behind": 0,
      "last_commit": "Tidy imports",
      "last_commit_at": 1789992800.0
     },
     "notification": {
      "title": "Claude Code",
      "subtitle": "Completed in Nimbus",
      "body": "Draft is in RELEASE_NOTES.md: 14 changes grouped into Features, Fixes, and Internal.",
      "created_at": "2026-09-23T17:00:00Z",
      "at": 1789992800.0,
      "read": false
     }
    }
   },
   {
    "sid": "2cf40948-b8ef-4e6f-8ea7-3572552e5e80",
    "state": "idle",
    "since": 1789928000.0,
    "last": 1789928000.0,
    "ws": "Scratch",
    "wid": "A91927FE-9749-491D-8DFA-D3C5BFDD7474",
    "surface": "E41EDD5E-7766-42FF-8B30-F80427CAFDA6",
    "title": "Claude Code",
    "repo": "scratch",
    "kind": "claude",
    "color": null,
    "cwd": "/Users/dev/code/scratch",
    "priority": null,
    "detail": {
     "hook": {
      "last_hook": "Stop",
      "tool": null,
      "tool_at": null,
      "tool_calls": 57,
      "prompts": 6,
      "turn_started": 1789927820.0,
      "tool_errors": null,
      "subagents_done": 2
     },
     "session": {
      "pid": 40011,
      "started_at": 1789982000.0,
      "account": "default",
      "transcript": null
     },
     "proc": {
      "cpu": 1,
      "rss_mb": 160,
      "etime": "05:00:00",
      "children": 1
     },
     "transcript": null,
     "workspace": {
      "description": null,
      "pinned": false,
      "group": null,
      "unread": 0,
      "window": 1,
      "branch": "main",
      "dirty": false,
      "ports": [],
      "prs": [],
      "latest_notification": null,
      "project_root": "/Users/dev/code/scratch",
      "remote": false
     },
     "git": {
      "branch": "main",
      "changed": 0,
      "ahead": 0,
      "behind": 0,
      "last_commit": "Tidy imports",
      "last_commit_at": 1789992800.0
     },
     "notification": null
    }
   },
   {
    "sid": "327f5f58-6ede-4dea-b5c6-30fdc4b2bf8c",
    "state": "idle",
    "since": 1789997600.0,
    "last": 1789997600.0,
    "ws": "Atlas",
    "wid": "A4D4C976-281C-45F7-AB96-345977668E2D",
    "surface": "66A62278-4AB4-4410-9A9F-80776514EF54",
    "title": "Refactor CLI flags",
    "repo": "atlas-cli",
    "kind": "codex",
    "color": "#4C8DFF",
    "cwd": "/Users/dev/code/atlas-cli",
    "priority": null,
    "detail": {
     "hook": {
      "last_hook": "Stop",
      "tool": null,
      "tool_at": null,
      "tool_calls": 57,
      "prompts": 6,
      "turn_started": 1789997420.0,
      "tool_errors": null,
      "subagents_done": 2
     },
     "session": {
      "pid": 40018,
      "started_at": 1789982000.0,
      "account": "default",
      "transcript": null
     },
     "proc": {
      "cpu": 1,
      "rss_mb": 160,
      "etime": "05:00:00",
      "children": 1
     },
     "transcript": null,
     "workspace": {
      "description": "Internal CLI for the Atlas platform",
      "pinned": false,
      "group": "Client B",
      "unread": 0,
      "window": 1,
      "branch": "main",
      "dirty": false,
      "ports": [],
      "prs": [],
      "latest_notification": null,
      "project_root": "/Users/dev/code/atlas-cli",
      "remote": false
     },
     "git": {
      "branch": "main",
      "changed": 0,
      "ahead": 0,
      "behind": 0,
      "last_commit": "Tidy imports",
      "last_commit_at": 1789992800.0
     },
     "notification": null
    }
   }
  ],
  "ended": [
   {
    "sid": "c54cde86-5a2c-42d3-b83d-1ba30308ca67",
    "state": "ended",
    "since": 1789982000.0,
    "last": 1789982000.0,
    "ws": "Ledger",
    "wid": "35608701-D828-4BC1-AFEE-D984D33CC9AA",
    "surface": "375D8EBE-AD18-4285-990A-A71764146909",
    "title": "Dependency audit",
    "repo": "ledger-api",
    "kind": "claude",
    "color": "#FF6B6B",
    "cwd": "/Users/dev/code/ledger-api",
    "priority": null,
    "detail": {
     "hook": {
      "last_hook": "Stop",
      "tool": null,
      "tool_at": null,
      "tool_calls": 57,
      "prompts": 6,
      "turn_started": 1789981820.0,
      "tool_errors": null,
      "subagents_done": 2
     },
     "session": {
      "pid": 40016,
      "started_at": 1789982000.0,
      "account": "work",
      "transcript": "/Users/dev/.claude/projects/-Users-dev-code-ledger-api/c54cde86-5a2c-42d3-b83d-1ba30308ca67.jsonl"
     },
     "proc": {
      "cpu": 1,
      "rss_mb": 160,
      "etime": "05:00:00",
      "children": 1
     },
     "transcript": {
      "ai_title": "Dependency audit",
      "model": "claude-opus-5",
      "effort": "high",
      "permission_mode": "auto",
      "mode": "normal",
      "git_branch": "main",
      "version": "2.1.280",
      "entrypoint": "cli",
      "turns": 6,
      "context_tokens": 120000,
      "output_tokens": 48000,
      "tool_errors": 1,
      "last_turn_ms": 42000,
      "message_count": 180,
      "last_user": "Audit dependencies for known CVEs.",
      "last_user_at": 1789981820.0,
      "last_prompt": "Audit dependencies for known CVEs.",
      "last_reply": "Done: bumped 9 packages, 2 need a major upgrade (tracked in #398).",
      "last_assistant_at": 1789982000.0,
      "files_edited": 0,
      "recent_files": [],
      "top_tools": [
       [
        "Bash",
        31
       ],
       [
        "Edit",
        12
       ],
       [
        "Read",
        9
       ],
       [
        "Grep",
        4
       ]
      ]
     },
     "workspace": {
      "description": null,
      "pinned": false,
      "group": "Client A",
      "unread": 0,
      "window": 1,
      "branch": "main",
      "dirty": false,
      "ports": [],
      "prs": [],
      "latest_notification": null,
      "project_root": "/Users/dev/code/ledger-api",
      "remote": false
     },
     "git": {
      "branch": "main",
      "changed": 0,
      "ahead": 0,
      "behind": 0,
      "last_commit": "Tidy imports",
      "last_commit_at": 1789992800.0
     },
     "notification": null
    }
   }
  ]
 },
 "totals": {
  "needs_input": 4,
  "working": 2,
  "idle": 3,
  "ended": 1
 }
});
